\abschnitt{exceptions}\label{exceptions}

%% In general,
If an uncaught exception escapes from a fiber's \entryfn,
\cpp{std::terminate} is called.
%% There is one exception: the \foreignex used to
%% unwind fiber stacks. The \fiber facility internally uses this \foreignex to
%% clean up the stack of a suspended fiber being destroyed. Because this
%% exception is a \foreignex, it can not be caught.
