\newpage
\abschnitt{Appendix A: support code for examples}\label{launch}\label{appendixa}

Destroying a non-empty \fiber instance invokes Undefined Behaviour -- you must
first call \anycancel (see \nameref{termination}). To simplify code examples in this paper, we introduce
an \cpp{autocancel} wrapper class that tracks the sequence of \fiber instances
representing a particular fiber. When an \cpp{autocancel} instance is
destroyed, it calls \cancel on the stored \fiber.

\cppf{autocancel}

The \fiber constructor accepts an \entryfn and a \cancelfn (see
\nameref{constructor}). Many of the examples in this paper are coded so that
every explicit fiber terminates by returning a non-empty \fiber instance from
its \entryfn. In such examples, \cancel never need be called. We pass a
trivial \cpp{assert\_on\_cancel()} function as shown:

\cppf{assert_cancel}

When \cpp{assert\_on\_cancel} is passed to a \fiber constructor as its \cancelfn,
if someone were to call \cancel on a \fiber instance representing that fiber,
\cpp{assert\_on\_cancel()} would fail its \cpp{assert()}.

Sometimes it is desirable to abandon a fiber without letting it run to
completion. Consider an infinite generator. For examples in which we abandon a
fiber, assume a \cpp{launch()} factory function that provides both an \entryfn
wrapper and a \cancelfn, as shown here:

\cppf{launch}

When a fiber is constructed by calling \cpp{launch()}, if the \cpp{autocancel}
instance representing that fiber is destroyed:

\begin{itemize}
    \item \cpp{\~autocancel()} calls \cpp{fiber\_context::cancel()} on the
          instance representing that fiber
    \item \cancel effectively calls \resumewith, passing
          the \cancelfn provided by \cpp{launch()}
    \item \resumewith switches context to the subject fiber, suspending the
          \cancel call
    \item the \cancelfn is passed a \fiber instance representing the fiber on
          which \cancel is suspended
    \item that \cancelfn constructs \cpp{unwind\_exception}, passing the
          synthesized \fiber instance
    \item \cpp{unwind\_exception}'s constructor move-constructs a heap \fiber
          instance from the passed \fiber instance
    \item \cpp{unwind\_exception} stores a \cpp{std::shared\_ptr} to that new
          heap \fiber instance
    \item the \cancelfn throws the new \cpp{unwind\_exception}
    \item the fiber stack is unwound according to normal C++ semantics
    \item the top-level wrapper provided by \cpp{launch()} catches the
          \cpp{unwind\_exception}
    \item the top-level wrapper extracts the \cpp{shared\_ptr}, dereferences
          it and returns the bound \fiber
    \item which terminates the fiber represented by the \cpp{autocancel}
          instance being destroyed
    \item and resumes the fiber calling \cancel.
\end{itemize}

A \cancelfn need not throw an exception -- it can instead, for instance,
change the state of an object observed by code running on the subject fiber.
Our examples use \cpp{launch()}, which throws \cpp{unwind\_exception}, so as
not to clutter the example code.
